### ISSUE TITLE
SLF4J Loggers should be CONSTANT

### ISSUE THREAD

**Issue by dhughes-xumak** [DantaFramework/Core#9]
Since SLF4J Logger is immutable, our `static final` reference constants should be all CAPS.  Here is one example:
https://github.com/DantaFramework/Core/blob/76f4c184bc7b232ac4e9b8ac5ea4485822956029/src/main/java/danta/core/util/OSGiUtils.java#L49

Further reading: https://stackoverflow.com/a/9510335

**Comment by dhughes-xumak** [comment]
label:enhancement

**Comment by jbarrera-xumak** [comment]
The changes were merged.
